apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: registry.gregsvc.fr/kawa-webshop-api/kawawebshopapi
      context: ../KawaWebshopAPI
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
