apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kawawebshopapi-postgresql-pvc
  namespace: mspr4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-main
---
apiVersion: v1
kind: Secret
metadata:
  name: kawawebshopapi-postgresql
  namespace: mspr4
  labels:
    app: kawawebshopapi-postgresql
type: Opaque
data:
  postgresql-password: ZjZlNTdmODRjNzA0MzlkMTI5YzAxN2RmMDAxMGRjYzkzN2ZjYzMxNjM3ZThhZGZjMDJiNTcwYjhjMjUz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kawawebshopapi-postgresql
  namespace: mspr4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kawawebshopapi-postgresql
  template:
    metadata:
      labels:
        app: kawawebshopapi-postgresql
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kawawebshopapi-postgresql-pvc
      containers:
        - name: postgres
          image: postgres:14.5
          env:
            - name: POSTGRES_USER
              value: KawaWebshopAPI
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kawawebshopapi-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: kawawebshopapi-postgresql
  namespace: mspr4
spec:
  selector:
    app: kawawebshopapi-postgresql
  ports:
    - port: 5432
